version: "3.9"
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=ACCESS_KEY"
      - "MINIO_SECRET_KEY=SECRET_KEY"
    command: server /export

  gh-server:
    image: node
    ports:
      - "12345:12345"
    entrypoint: ["/bin/sh", "-c", "npm install && npx babel-node e2e/server.js"]
    volumes:
      - "../:/srv/"
    working_dir: "/srv/"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 15;
      /usr/bin/mc config host add myminio http://minio:9000 ACCESS_KEY SECRET_KEY;
      /usr/bin/mc rm -r --force myminio/swatcher-bucket;
      /usr/bin/mc mb myminio/swatcher-bucket;
      /usr/bin/mc policy set download myminio/swatcher-bucket;
      exit 0;
      "
