on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - run: npx gulp
      - run: bash <(curl -s https://codecov.io/bash)
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf dist
        name: remove dist folder before running linter 
      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (!context.payload.pull_request) {
              console.log('Not pull request')
              return
            }
            const files = await github.paginate(github.pulls.listFiles, { owner: context.repo.owner, repo: context.repo.repo, pull_number: context.payload.pull_request.number})
            files.forEach(file => {
              if (file.filename === 'dist/index.js') throw new Error('You accidentally commited "dist/index.js". This file should be generated only by CD. Run "git checkout master dist/index.js"')
              if (file.filename === 'version.js') throw new Error('You accidentally commited "version.js". This file should be generated only by CD. Run "git checkout master version.js"')
            })
  
  build_dist:
    runs-on: ubuntu-latest
    needs: [test, lint, check-files]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
      - run: npm ci
      - run: npx gulp
      - run: chmod +x dist/index.js
      - run: |
          git add -f dist version.js package.json package-lock.json
          git commit -m "Automatically built distribution package"
          git push
